### PR TITLE
allow delete from other namespaces

### PR DESCRIPTION
**Pull request by valentin2105**
😸

### CODE REVIEW

**Comment by c9s** [comment]
Oh conflict

**Comment by c9s** [comment]
You might need to rebase

**Comment by valentin2105** [comment]
seem good ?

**Comment by c9s** [comment]
@valentin2105 the s:cmdbase() function already provides the namespace option :) I added it few days ago

**Comment by c9s** [comment]
Already implemented in the s:cmdbase()

**Pull request closed without merging**
